package zw.co.cryptosine.rava.enums;

public enum RavaSubject {
    ENGLISH, MATHEMATICS, SHONA, SCIENCE, CHEMESTRY, PHYSICS, BIOLOGY, BIBLE_STUDIES, COMPUTING, ACCOUNTING, ECONOMICS, BUSINESS_STUDIES, GEOGRAPHY, ZIMBAWE_HISTORY
}
